server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: "debug"

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://tasks.loki:3100/loki/api/v1/push

scrape_configs:
- job_name: traefik
  static_configs:
  - targets:
    - localhost
    labels:
      job: traefix-access
      __path__: /var/log/traefik/*.json
