- name: deploy docker and media user/group
  hosts: localhost
  become: true
  become_method: sudo

  roles:
    - role: users
    - role: docker-install
      docker__users: ["{{ local_user }}", "{{ media_username }}"]
    - role: docker-setup
